/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory, } from "@stencil/router";
export namespace Components {
    interface AppChapter {
        "match": MatchResults;
    }
    interface AppChapterContent {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppChapterElement extends Components.AppChapter, HTMLStencilElement {
    }
    var HTMLAppChapterElement: {
        prototype: HTMLAppChapterElement;
        new (): HTMLAppChapterElement;
    };
    interface HTMLAppChapterContentElement extends Components.AppChapterContent, HTMLStencilElement {
    }
    var HTMLAppChapterContentElement: {
        prototype: HTMLAppChapterContentElement;
        new (): HTMLAppChapterContentElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-chapter": HTMLAppChapterElement;
        "app-chapter-content": HTMLAppChapterContentElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppChapter {
        "match"?: MatchResults;
    }
    interface AppChapterContent {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-chapter": AppChapter;
        "app-chapter-content": AppChapterContent;
        "app-home": AppHome;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-chapter": LocalJSX.AppChapter & JSXBase.HTMLAttributes<HTMLAppChapterElement>;
            "app-chapter-content": LocalJSX.AppChapterContent & JSXBase.HTMLAttributes<HTMLAppChapterContentElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
